### ISSUE TITLE
"format" argument not being used

### ISSUE THREAD

**Issue by static-electron** [gladed/gradle-android-git-version#51] opened 2018-06-29 01:14 UTC
When I try to build on a non-tagged version the "format" argument is not respected.
My setup looks like this:

  androidGitVersion {
        // Code format is determined from the most recent tag, eg 5.0.1
        // M: major number (5)
        // N: minor number (0)
        // P: patch number (1)
        // B: build number (# of git revisions since the last tag)
        codeFormat = 'MNNPPPBBB'
        format = '%tag%--%count%'
  }

But the version name looks like this:
`5.0.0-RC0-7-d9b05be-d9b05be320ff9b68bb4ff8b72077faafb939d1f3`

**Comment by gladed** [comment] 2018-06-29 17:01
I can't reproduce this. Are you sure no other gradle code is setting the name? What is the output from `./gradlew androidGitVersion`?

Remember its required to manually apply the name with `android.defaultConfig.versionName = androidGitVersion.name()` or similar.

**Comment by gladed** [comment] 2018-12-10 19:21
Closing because I cannot reproduce.

**Closed as completed** 2018-12-10 19:28 UTC
