### ISSUE TITLE
Recommended tagPattern format produce syntax error.

### ISSUE THREAD

**Issue by jkbgntr94** [gladed/gradle-android-git-version#50] opened 2018-06-21 09:01 UTC
When i add tagPattern from readme tagPattern /^v[0-9]+.*/ i cant sync gradle because of syntax error. I tried quotation marks and many other possible solutions but without success. When i use "" or '' pattern is ignored and tag is untagged. I have gradle version 3.0.1. 
Is there any possible solution for that? 
Thanks.

`androidGitVersion {
    baseCode 1
    codeFormat 'MNNPPP'
    format "%tag%%-commit%%-dirty%"
    tagPattern /^v[0-9]+.*/

}`

**Comment by gladed** [comment] 2018-06-22 17:44
I tried running the unit tests with gradle 3.0.1 and they worked fine. Can you share the exact syntax error you received and perhaps the tag name?

**Comment by gladed** [comment] 2018-12-10 19:28
Cannot reproduce, closing

**Closed as completed by gladed** 2018-12-10 19:28 UTC
